name: terraform_test

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: '50 23 * * *' # 每日定时触发
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Set up AliCloud credentials
        run: |
          echo "ALICLOUD_ACCESS_KEY=${{ secrets.ALICLOUD_ACCESS_KEY }}" >> $GITHUB_ENV
          echo "ALICLOUD_SECRET_KEY=${{ secrets.ALICLOUD_SECRET_KEY }}" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      # - name: Generate Report
      #   run: |
      #     # 这里添加生成报告的命令
      #     echo "Generate and publish report"

      - name: Terraform destroy
        run: terraform destroy

      # - name: Publish to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./reports
